services:
    migration:
        build: .
        command: python manage.py migrate --noinput
        volumes:
            - .:/code
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/code
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - migration
