# Generated by Django 4.1.3 on 2022-11-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221105_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_amount',
            field=models.IntegerField(default=0),
        ),
    ]
