# Generated by Django 4.1.3 on 2022-11-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_likes_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_amount',
            field=models.IntegerField(default=0),
        ),
    ]
